name: BalenaCloud Push

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - main

jobs:
  balena-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - uses: theaccordance/balena-push@v1.0.0
      with:
        api-token: ${{secrets.BALENA_API_TOKEN}}
        application-name: HELIUM-EU868
  balena-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - uses: theaccordance/balena-push@v1.0.0
      with:
        api-token: ${{secrets.BALENA_API_TOKEN}}
        application-name: HELIUM-US915
